/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'TestFtspMsg'
 * message type.
 */

public class TestFtspMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 8;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 137;

    /** Create a new TestFtspMsg of size 8. */
    public TestFtspMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new TestFtspMsg of the given data_length. */
    public TestFtspMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestFtspMsg with the given data_length
     * and base offset.
     */
    public TestFtspMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestFtspMsg using the given byte array
     * as backing store.
     */
    public TestFtspMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestFtspMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public TestFtspMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestFtspMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public TestFtspMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestFtspMsg embedded in the given message
     * at the given base offset.
     */
    public TestFtspMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestFtspMsg embedded in the given message
     * at the given base offset and length.
     */
    public TestFtspMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <TestFtspMsg> \n";
      try {
        s += "  [src_addr=0x"+Long.toHexString(get_src_addr())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [counter=0x"+Long.toHexString(get_counter())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [global_rx_timestamp=0x"+Long.toHexString(get_global_rx_timestamp())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: src_addr
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'src_addr' is signed (false).
     */
    public static boolean isSigned_src_addr() {
        return false;
    }

    /**
     * Return whether the field 'src_addr' is an array (false).
     */
    public static boolean isArray_src_addr() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'src_addr'
     */
    public static int offset_src_addr() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'src_addr'
     */
    public static int offsetBits_src_addr() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'src_addr'
     */
    public int get_src_addr() {
        return (int)getUIntBEElement(offsetBits_src_addr(), 16);
    }

    /**
     * Set the value of the field 'src_addr'
     */
    public void set_src_addr(int value) {
        setUIntBEElement(offsetBits_src_addr(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'src_addr'
     */
    public static int size_src_addr() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'src_addr'
     */
    public static int sizeBits_src_addr() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: counter
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'counter' is signed (false).
     */
    public static boolean isSigned_counter() {
        return false;
    }

    /**
     * Return whether the field 'counter' is an array (false).
     */
    public static boolean isArray_counter() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'counter'
     */
    public static int offset_counter() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'counter'
     */
    public static int offsetBits_counter() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'counter'
     */
    public int get_counter() {
        return (int)getUIntBEElement(offsetBits_counter(), 16);
    }

    /**
     * Set the value of the field 'counter'
     */
    public void set_counter(int value) {
        setUIntBEElement(offsetBits_counter(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'counter'
     */
    public static int size_counter() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'counter'
     */
    public static int sizeBits_counter() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: global_rx_timestamp
    //   Field type: long, unsigned
    //   Offset (bits): 32
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'global_rx_timestamp' is signed (false).
     */
    public static boolean isSigned_global_rx_timestamp() {
        return false;
    }

    /**
     * Return whether the field 'global_rx_timestamp' is an array (false).
     */
    public static boolean isArray_global_rx_timestamp() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'global_rx_timestamp'
     */
    public static int offset_global_rx_timestamp() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'global_rx_timestamp'
     */
    public static int offsetBits_global_rx_timestamp() {
        return 32;
    }

    /**
     * Return the value (as a long) of the field 'global_rx_timestamp'
     */
    public long get_global_rx_timestamp() {
        return (long)getUIntBEElement(offsetBits_global_rx_timestamp(), 32);
    }

    /**
     * Set the value of the field 'global_rx_timestamp'
     */
    public void set_global_rx_timestamp(long value) {
        setUIntBEElement(offsetBits_global_rx_timestamp(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'global_rx_timestamp'
     */
    public static int size_global_rx_timestamp() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'global_rx_timestamp'
     */
    public static int sizeBits_global_rx_timestamp() {
        return 32;
    }

}
